include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = LSTSPrefs

LSTSPrefs_FILES = LSTRootListController.m
LSTSPrefs_FRAMEWORKS = UIKit
LSTSPrefs_PRIVATE_FRAMEWORKS = Preferences
LSTSPrefs_INSTALL_PATH = /Library/PreferenceBundles
LSTSPrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
